### ISSUE TITLE
KEGG REST API for link with genes DB has changed

### ISSUE THREAD

**Issue by peterjc** [widdowquinn/2018-03-06-ibioic#4]
As noted by @widdowquinn at least one of the KEGG REST API examples has stopped working.

Minimal Biopython test case, based on ``09-KEGG_programming.ipynb``

```
$ python -c 'from Bio.KEGG.REST import kegg_link; print(kegg_link("genes", "ksk00061").read())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xxx/lib/python3.5/site-packages/Bio/KEGG/REST.py", line 296, in kegg_link
    resp = _q("link", target_db, source_db)
  File "/home/xxx/lib/python3.5/site-packages/Bio/KEGG/REST.py", line 42, in _q
    resp = _urlopen(URL % (args))
  File "/home/xxx/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/home/xx/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/home/xxx/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/xxx/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/home/xxx/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/home/xxx/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

Using curl:

```
$ curl -v http://rest.kegg.jp/link/genes/ksk00061
*   Trying 133.103.200.77...
* TCP_NODELAY set
* Connected to rest.kegg.jp (133.103.200.77) port 80 (#0)
> GET /link/genes/ksk00061 HTTP/1.1
> Host: rest.kegg.jp
> User-Agent: curl/7.54.1
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Date: Wed, 21 Feb 2018 11:05:16 GMT
< Server: Apache
< Content-Length: 0
< Connection: close
< Content-Type: text/plain
< 
* Closing connection 0
```

The KEGG documentation http://www.kegg.jp/kegg/rest/keggapi.html#link gives http://rest.kegg.jp/link/genes/K00500 as an example, and that is working fine:

```
$ curl http://rest.kegg.jp/link/genes/K00500
ko:K00500	hsa:5053
...
ko:K00500	ial:IALB_1335
```

Also fine via Biopython,

```
$ python -c 'from Bio.KEGG.REST import kegg_link; print(kegg_link("genes", "K00500").read())'
ko:K00500	hsa:5053
...
ko:K00500	ial:IALB_1335
```

Quoting http://www.kegg.jp/kegg/rest/keggapi.html#link

> This operation allows retrieval of cross-references within all KEGG databases, as well as pubmed. It is useful for finding various relationships, such as relationships between genes and pathways. The first form allows retrieval of database to database cross-references, while the second form allows retrieval for a selected number of entries. The database name "genes" may be used only for "ko" entries in the second form.

Here we are using the second form of the ``link`` API, where the arguments are a database (here ``genes``) and the second is entries from that database. It seems this explicitly requires KO entries in this case.

This text is new, quoting https://web.archive.org/web/20170429173916/http://www.kegg.jp/kegg/rest/keggapi.html (archive from April 2017), this text was just:

> The database name "genes" may be used only in the second form.

Quoting https://web.archive.org/web/20170602093216/http://www.kegg.jp:80/kegg/rest/keggapi.html (archive from 2 June 2017), the text was:

> This operation allows retrieval of cross-references within all KEGG databases, as well as pubmed. It is useful for finding various relationships, such as relationships between genes and pathways. The first form allows retrieval of database to database cross-references, while the second form allows retrieval for a selected number of entries. The database name "genes" may be used only in the second form.

The key sentence was added between 26 June 2017 and 3 July 2017, quoting https://web.archive.org/web/20170703234134/http://www.kegg.jp:80/kegg/rest/keggapi.html

> This operation allows retrieval of cross-references within all KEGG databases, as well as pubmed. It is useful for finding various relationships, such as relationships between genes and pathways. The first form allows retrieval of database to database cross-references, while the second form allows retrieval for a selected number of entries. The database name "genes" may be used only for "ko" entries in the second form.

**Comment by peterjc** [comment]
I could see nothing specific about this June/July 2017 ``link`` change in the update history on http://www.kegg.jp/kegg/rest/ but there was an older announcement from 2015 which is somewhat relevant:

> Notice to KEGG API users: conv and link problems 
>
> Since around August 21, the update of the LinkDB database at GenomeNet has become unstable due to the huge increase of the data size. As the result, the conv and link operations of KEGG API sometimes do not return any result. 
>
> We are working on a new method that does not depend on LinkDB.
> In the meantime please report any problems through the KEGG/GenomeNet feedback form. 
>
> Posted on September 22, 2015

**Comment by peterjc** [comment]
So, we can now only use ``http://rest.kegg.jp/link/genes/...`` with ``ko`` entries (KEGG orthology).

The goal of the example was to get all the genes in pathway ``ksk00061`` which is "Fatty acid biosynthesis - Kitasatospora setae", and the website http://www.kegg.jp/entry/ksk00061 does list the genes...

```
$ python -c 'from Bio.KEGG.REST import kegg_get; print(kegg_get("ksk00061").read())'
ENTRY       ksk00061                    Pathway
NAME        Fatty acid biosynthesis - Kitasatospora setae
CLASS       Metabolism; Lipid metabolism
PATHWAY_MAP ksk00061  Fatty acid biosynthesis
MODULE      ksk_M00082  Fatty acid biosynthesis, initiation [PATH:ksk00061]
            ksk_M00083  Fatty acid biosynthesis, elongation [PATH:ksk00061]
ORGANISM    Kitasatospora setae [GN:ksk]
GENE        KSE_65020  putative acyl-CoA carboxylase [KO:K01962 K01963] [EC:2.1.3.15 6.4.1.2 2.1.3.15 6.4.1.2]
            KSE_72490  putative acyl-CoA carboxylase [KO:K01962 K01963] [EC:2.1.3.15 6.4.1.2 2.1.3.15 6.4.1.2]
            KSE_72500  putative acyl-CoA carboxylase [KO:K02160]
...
```

We could then parse this, or just leave the example like that with the human readable text?

**Comment by peterjc** [comment]
As discussed with @widdowquinn  the simplest solution is to remove this specific example from the notebook. I think the *Retrieving pathway components* can still flow nicely without it.

**Comment by widdowquinn** [comment]
I think you're right. I'll take a run through the material and see how it flows with that bit removed. I expect it will be gone for the presentation.

**Comment by widdowquinn** [comment]
Rather than remove it, I've changed the combination of queries, so we're now searching with `map00061` against the `COMPOUND` database. This all seems to work, for now.
