### ISSUE TITLE
Incorrect BLASTP parsing parameter 

### ISSUE THREAD

**Issue by Tim-Kirkwood** [widdowquinn/2018-03-06-ibioic#45]
Hello!  

I'm building an RBH pipeline and found your quick script approach for achieving this (https://widdowquinn.github.io/2018-03-06-ibioic/02-sequence_databases/05-blast_for_rbh.html).  It's a (really) nice page/educational resource with clear explanations.  Unfortunately, I think you are using an incorrect BLAST setting.  You say: 

> 'We can use two features of command-line BLAST that make our job easier later.
> 
> We will restrict the number of matches to be returned to 1, by using the -max_target_seqs argument. This will only report the best database hit to each query. We will not need to build a separate "best hit table".'

However, -max_target_seqs doesn't return the best hit, just the first hit (Shah et al 2019), so you are comparing first hits not best hits with your RBH approach (if I understand correctly).

Thanks :D

Nidhi Shah, Michael G Nute, Tandy Warnow, Mihai Pop, Misunderstood parameter of NCBI BLAST impacts the correctness of bioinformatics workflows, Bioinformatics, Volume 35, Issue 9, 1 May 2019, Pages 1613–1614, https://doi.org/10.1093/bioinformatics/bty833

**Comment by peterjc** [comment]
Don't take Shah *et al.* 2018 at face value, see the reply from the BLAST authors https://doi.org/10.1093/bioinformatics/bty1026 or my own digging: https://blastedbio.blogspot.com/2019/01/blast-overly-aggressive-optimization.html

(Update, fixed the year of the first paper)

**Comment by Tim-Kirkwood** [comment]
Thanks for your response, I was in the process of reading your blog posts on this actually (after I raised the issue) - they clarify things nicely.
